package com.rendevous.intention.trick.spring.model;
// Generated Jun 14, 2013 11:16:06 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERS", catalog = "cherryDB")
public class Customers implements java.io.Serializable {

	private Integer customerId;
	private String firstName;
	private String middleInitial;
	private String lastName;
	private String emailAddress;
	private String userId;
	private String userPassword;
	private String confirmUserPassword;	
	private boolean acceptedTermsAndConditions;	
	private String phoneNumber;
	private Date registrationDate;
	private Date lastLoginDate;
	private String customerType;
	private String businessName;
	private Integer userRoles;
	private String activationCode;
	private String accountStatusReason;
	private String accountStatusCode;
	private String tempPassword;
	
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(
			0);
	private Set<CustomerPaymentInformation> customerPaymentInformations = new HashSet<CustomerPaymentInformation>(
			0);
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<CustomerBids> customerBidses = new HashSet<CustomerBids>(0);

	public Customers() {
	}

	public Customers(String firstName, String middleInitial,
			String lastName, String emailAddress, String userId,
			String userPassword, String confirmUserPassword, boolean acceptedTermsAndConditions, String phoneNumber, Date registrationDate,
			Date lastLoginDate, String customerType, String businessName, Integer userRoles, String activationCode,
			String accountStatusReason, String accountStatusCode, String tempPassword,
			Set<CustomerAddress> customerAddresses,
			Set<CustomerPaymentInformation> customerPaymentInformations,
			Set<Items> itemses, Set<CustomerBids> customerBidses) {
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.userId = userId;
		this.userPassword = userPassword;
		this.confirmUserPassword = confirmUserPassword;
		this.acceptedTermsAndConditions=acceptedTermsAndConditions;
		this.phoneNumber = phoneNumber;
		this.registrationDate = registrationDate;
		this.lastLoginDate = lastLoginDate;
		this.customerType = customerType;
		this.businessName = businessName;
		this.userRoles = userRoles;
		this.activationCode = activationCode;
		this.accountStatusReason = accountStatusReason;
		this.accountStatusCode = accountStatusCode;
		this.tempPassword = tempPassword;
		this.customerAddresses = customerAddresses;
		this.customerPaymentInformations = customerPaymentInformations;
		this.itemses = itemses;
		this.customerBidses = customerBidses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_INITIAL", length = 30)
	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ADDRESS", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "USER_ID", length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_PASSWORD", length = 100)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
	
	
	@Column(name = "TEMP_PASSWORD", length = 100)
	public String getTempPassword() {
		return this.tempPassword;
	}

	public void setTempPassword(String tempPassword) {
		this.tempPassword = tempPassword;
	}
	
	
	@Transient
	public String getConfirmUserPassword() {
		return confirmUserPassword;
	}

	public void setConfirmUserPassword(String confirmUserPassword) {
		this.confirmUserPassword = confirmUserPassword;
	}

	@Transient
	public boolean getAcceptedTermsAndConditions() {
		return acceptedTermsAndConditions;
	}

	public void setAcceptedTermsAndConditions(boolean acceptedTermsAndConditions) {
		this.acceptedTermsAndConditions = acceptedTermsAndConditions;
	}

	
	@Column(name = "PHONE_NUMBER", length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGISTRATION_DATE", length = 19)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_DATE", length = 19)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Column(name = "CUSTOMER_TYPE", length = 30)
	public String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	@Column(name = "BUSINESS_NAME", length = 50)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}
	
	@Column(name = "USER_ROLES")
	public Integer getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Integer userRoles) {
		this.userRoles = userRoles;
	}
	
	@Column(name = "ACTIVATION_CODE", length = 150)
	public String getActivationCode() {
		return this.activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

	@Column(name = "ACCOUNT_STATUS_REASON", length = 20)
	public String getAccountStatusReason() {
		return this.accountStatusReason;
	}

	public void setAccountStatusReason(String accountStatusReason) {
		this.accountStatusReason = accountStatusReason;
	}

	@Column(name = "ACCOUNT_STATUS_CODE", length = 3)
	public String getAccountStatusCode() {
		return this.accountStatusCode;
	}

	public void setAccountStatusCode(String accountStatusCode) {
		this.accountStatusCode = accountStatusCode;
	}
	

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customers")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customers")
	public Set<CustomerPaymentInformation> getCustomerPaymentInformations() {
		return this.customerPaymentInformations;
	}

	public void setCustomerPaymentInformations(
			Set<CustomerPaymentInformation> customerPaymentInformations) {
		this.customerPaymentInformations = customerPaymentInformations;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customers")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customers")
	public Set<CustomerBids> getCustomerBidses() {
		return this.customerBidses;
	}

	public void setCustomerBidses(Set<CustomerBids> customerBidses) {
		this.customerBidses = customerBidses;
	}

}
