package com.rendevous.intention.trick.spring.model;
// Generated Jun 14, 2013 11:16:06 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerBids generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER_BIDS", catalog = "cherryDB")
public class CustomerBids implements java.io.Serializable {

	private Integer bidId;
	private Customers customers;
	private Items items;
	private String bidPrice;
	private String winnginBid;
	private Date bidDate;

	public CustomerBids() {
	}

	public CustomerBids(Customers customers, Items items, String bidPrice,
			String winnginBid, Date bidDate) {
		this.customers = customers;
		this.items = items;
		this.bidPrice = bidPrice;
		this.winnginBid = winnginBid;
		this.bidDate = bidDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BID_ID", unique = true, nullable = false)
	public Integer getBidId() {
		return this.bidId;
	}

	public void setBidId(Integer bidId) {
		this.bidId = bidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "BID_PRICE", length = 15)
	public String getBidPrice() {
		return this.bidPrice;
	}

	public void setBidPrice(String bidPrice) {
		this.bidPrice = bidPrice;
	}

	@Column(name = "WINNGIN_BID", length = 5)
	public String getWinnginBid() {
		return this.winnginBid;
	}

	public void setWinnginBid(String winnginBid) {
		this.winnginBid = winnginBid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BID_DATE", length = 19)
	public Date getBidDate() {
		return this.bidDate;
	}

	public void setBidDate(Date bidDate) {
		this.bidDate = bidDate;
	}

}
