package com.rendevous.intention.trick.spring.model;
// Generated Jul 24, 2013 4:36:42 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerPaymentInformation generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER_PAYMENT_INFORMATION", catalog = "cherryDB")
public class CustomerPaymentInformation implements java.io.Serializable {

	private Integer paymentCardId;
	private Customers customers;
	private String nameOnCard;
	private String billingContactPhoneNumber;
	private String cardType;
	private String cardExpirationMonth;
	private String cardExpirationYear;
	private String cardNumber;
	private String cvv;

	public CustomerPaymentInformation() {
	}

	public CustomerPaymentInformation(Customers customers, String nameOnCard,
			String billingContactPhoneNumber, String cardType,
			String cardExpirationMonth, String cardExpirationYear,
			String cardNumber, String cvv) {
		this.customers = customers;
		this.nameOnCard = nameOnCard;
		this.billingContactPhoneNumber = billingContactPhoneNumber;
		this.cardType = cardType;
		this.cardExpirationMonth = cardExpirationMonth;
		this.cardExpirationYear = cardExpirationYear;
		this.cardNumber = cardNumber;
		this.cvv = cvv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PAYMENT_CARD_ID", unique = true, nullable = false)
	public Integer getPaymentCardId() {
		return this.paymentCardId;
	}

	public void setPaymentCardId(Integer paymentCardId) {
		this.paymentCardId = paymentCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@Column(name = "NAME_ON_CARD", length = 150)
	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	@Column(name = "BILLING_CONTACT_PHONE_NUMBER", length = 15)
	public String getBillingContactPhoneNumber() {
		return this.billingContactPhoneNumber;
	}

	public void setBillingContactPhoneNumber(String billingContactPhoneNumber) {
		this.billingContactPhoneNumber = billingContactPhoneNumber;
	}

	@Column(name = "CARD_TYPE", length = 50)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "CARD_EXPIRATION_MONTH", length = 2)
	public String getCardExpirationMonth() {
		return this.cardExpirationMonth;
	}

	public void setCardExpirationMonth(String cardExpirationMonth) {
		this.cardExpirationMonth = cardExpirationMonth;
	}

	@Column(name = "CARD_EXPIRATION_YEAR", length = 4)
	public String getCardExpirationYear() {
		return this.cardExpirationYear;
	}

	public void setCardExpirationYear(String cardExpirationYear) {
		this.cardExpirationYear = cardExpirationYear;
	}

	@Column(name = "CARD_NUMBER", length = 25)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "CVV", length = 5)
	public String getCvv() {
		return this.cvv;
	}

	public void setCvv(String cvv) {
		this.cvv = cvv;
	}

}
