package com.rendevous.intention.trick.spring.model;

// Generated Jun 14, 2013 11:16:06 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "ITEMS", catalog = "cherryDB")
public class Items implements java.io.Serializable {

	private Integer itemId;
	private Customers customers;
	private String itemName;
	private String itemDescription;
	private String itemPrice;
	private String businessName;
	private String itemCurrentBidPrice;	
	private String itemQuantityAvailable;
	private String itemImageLocation1;
	private String itemImageLocation2;
	private String itemImageLocation3;
	private String itemImageLocation4;
	private String itemImageLocation5;
	private String itemImageLocation6;
	private Date itemAddedDate;
	private Date itemModifiedDate;
	private Date itemSoldDate;
	private Date itemFinalTimeToBid;
	private String tempItemFinalTimeToBid;	
	private String itemFinalTimeToBidTimezone;
	private String itemStatusReason;
	private String itemStatusCode;
	private Set<CustomerBids> customerBidses = new HashSet<CustomerBids>(0);
	private List<MultipartFile> files;

	public Items() {
	}

	public Items(Customers customers, String itemName, String itemDescription,
			String itemPrice, String businessName, String itemCurrentBidPrice,
			String itemQuantityAvailable, String itemImageLocation1,
			String itemImageLocation2, String itemImageLocation3,
			String itemImageLocation4, String itemImageLocation5,
			String itemImageLocation6, Date itemAddedDate,Date itemModifiedDate, Date itemSoldDate,
			String itemStatusReason, String itemStatusCode, String itemFinalTimeToBidTimezone,
			Date itemFinalTimeToBid, String tempItemFinalTimeToBid, Set<CustomerBids> customerBidses) {
		this.customers = customers;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		this.itemPrice = itemPrice;
		this.businessName = businessName;
		this.itemCurrentBidPrice = itemCurrentBidPrice;
		this.itemQuantityAvailable = itemQuantityAvailable;
		this.itemImageLocation1 = itemImageLocation1;
		this.itemImageLocation2 = itemImageLocation2;
		this.itemImageLocation3 = itemImageLocation3;
		this.itemImageLocation4 = itemImageLocation4;
		this.itemImageLocation5 = itemImageLocation5;
		this.itemImageLocation6 = itemImageLocation6;
		this.itemAddedDate = itemAddedDate;
		this.itemAddedDate = itemModifiedDate;
		this.itemSoldDate = itemSoldDate;
		this.itemFinalTimeToBid = itemFinalTimeToBid;
		this.tempItemFinalTimeToBid = tempItemFinalTimeToBid;		
		this.itemFinalTimeToBidTimezone = itemFinalTimeToBidTimezone;
		this.itemStatusReason = itemStatusReason;
		this.itemStatusCode = itemStatusCode;
		this.customerBidses = customerBidses;
	}

	
	@Transient
	public List<MultipartFile> getFiles() {
		return files;
	}

	public void setFiles(List<MultipartFile> files) {
		this.files = files;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_ID", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_OWNER_CUSTOMER_ID")
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@Column(name = "ITEM_NAME", length = 150)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 500)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "ITEM_PRICE", length = 15)
	public String getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(String itemPrice) {
		this.itemPrice = itemPrice;
	}
	
	@Column(name = "ITEM_CURRENT_BID_PRICE", length = 15)
	public String getItemCurrentBidPrice() {
		return this.itemCurrentBidPrice;
	}

	public void setItemCurrentBidPrice(String itemCurrentBidPrice) {
		this.itemCurrentBidPrice = itemCurrentBidPrice;
	}

	@Column(name = "ITEM_QUANTITY_AVAILABLE", length = 15)
	public String getItemQuantityAvailable() {
		return this.itemQuantityAvailable;
	}

	public void setItemQuantityAvailable(String itemQuantityAvailable) {
		this.itemQuantityAvailable = itemQuantityAvailable;
	}

	@Column(name = "ITEM_IMAGE_LOCATION1", length = 100)
	public String getItemImageLocation1() {
		return this.itemImageLocation1;
	}

	public void setItemImageLocation1(String itemImageLocation1) {
		this.itemImageLocation1 = itemImageLocation1;
	}

	@Column(name = "ITEM_IMAGE_LOCATION2", length = 100)
	public String getItemImageLocation2() {
		return this.itemImageLocation2;
	}

	public void setItemImageLocation2(String itemImageLocation2) {
		this.itemImageLocation2 = itemImageLocation2;
	}

	@Column(name = "ITEM_IMAGE_LOCATION3", length = 100)
	public String getItemImageLocation3() {
		return this.itemImageLocation3;
	}

	public void setItemImageLocation3(String itemImageLocation3) {
		this.itemImageLocation3 = itemImageLocation3;
	}

	@Column(name = "ITEM_IMAGE_LOCATION4", length = 100)
	public String getItemImageLocation4() {
		return this.itemImageLocation4;
	}

	public void setItemImageLocation4(String itemImageLocation4) {
		this.itemImageLocation4 = itemImageLocation4;
	}

	@Column(name = "ITEM_IMAGE_LOCATION5", length = 100)
	public String getItemImageLocation5() {
		return this.itemImageLocation5;
	}

	public void setItemImageLocation5(String itemImageLocation5) {
		this.itemImageLocation5 = itemImageLocation5;
	}

	@Column(name = "ITEM_IMAGE_LOCATION6", length = 100)
	public String getItemImageLocation6() {
		return this.itemImageLocation6;
	}

	public void setItemImageLocation6(String itemImageLocation6) {
		this.itemImageLocation6 = itemImageLocation6;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITEM_ADDED_DATE", length = 19)
	public Date getItemAddedDate() {
		return this.itemAddedDate;
	}

	public void setItemAddedDate(Date itemAddedDate) {
		this.itemAddedDate = itemAddedDate;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITEM_MODIFIED_DATE", length = 19)
	public Date getItemModifiedDate() {
		return this.itemModifiedDate;
	}

	public void setItemModifiedDate(Date itemModifiedDate) {
		this.itemModifiedDate = itemModifiedDate;
	}
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITEM_SOLD_DATE", length = 19)
	public Date getItemSoldDate() {
		return this.itemSoldDate;
	}

	public void setItemSoldDate(Date itemSoldDate) {
		this.itemSoldDate = itemSoldDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITEM_FINAL_TIME_TO_BID", length = 19)
	public Date getItemFinalTimeToBid() {
		return this.itemFinalTimeToBid;
	}

	public void setItemFinalTimeToBid(Date itemFinalTimeToBid) {
		this.itemFinalTimeToBid = itemFinalTimeToBid;
	}
	
	
	@Column(name = "TEMP_ITEM_FINAL_TIME_TO_BID", length = 150)
	public String getTempItemFinalTimeToBid() {
		return tempItemFinalTimeToBid;
	}

	public void setTempItemFinalTimeToBid(String tempItemFinalTimeToBid) {
		this.tempItemFinalTimeToBid = tempItemFinalTimeToBid;
	}
	
	
	@Column(name = "ITEM_FINAL_TIME_TO_BID_TIMEZONE", length = 100)
	public String getItemFinalTimeToBidTimezone() {
		return this.itemFinalTimeToBidTimezone;
	}

	public void setItemFinalTimeToBidTimezone(String itemFinalTimeToBidTimezone) {
		this.itemFinalTimeToBidTimezone = itemFinalTimeToBidTimezone;
	}
	
	@Column(name = "ITEM_STATUS_REASON", length = 100)
	public String getItemStatusReason() {
		return this.itemStatusReason;
	}

	public void setItemStatusReason(String itemStatusReason) {
		this.itemStatusReason = itemStatusReason;
	}

	@Column(name = "ITEM_STATUS_CODE", length = 3)
	public String getItemStatusCode() {
		return this.itemStatusCode;
	}

	public void setItemStatusCode(String itemStatusCode) {
		this.itemStatusCode = itemStatusCode;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<CustomerBids> getCustomerBidses() {
		return this.customerBidses;
	}

	public void setCustomerBidses(Set<CustomerBids> customerBidses) {
		this.customerBidses = customerBidses;
	}
	
	
	@Column(name = "BUSINESS_NAME", length = 50)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}
	

}
